module.exports = {
  movie: [
    '<div class="movie" data-id="<%=_id%>">',
      '<h1><%= movieTitle%></h1>',
      '<img src="<%=coverImg%>" alt="" />',
      '<span>Rating:<%=rating%></span>',
      '<p>',
      '<%=plot%>',
      '</p>',
      '<button class = "delete" type="button" name="button">Delete</button>',
    '</div>'

  ].join(""),
  form: [
    '<div class="container">',
    '<form class = "first-form" role="form">',
  '<div class="form-group">',
    '<label for="title">Movie Title:</label>',
'    <input type="text" class="form-control" textarea= "movie title" id="title">',
  '</div>',
  '<div class="form-group">',
    '<label for="release">Release Year:</label>',
    '<input type="text" class="form-control" id="release">',
  '</div>',
  '<div class="form-group">',
    '<label for="cover">Cover Img:</label>',
    '<input type="text" class="form-control" id="cover">',
  '</div>',
  '<div class="form-group">',
    '<label for="plot">Plot:</label>',
    '<input type="text" class="form-control" id="plots">',
  '</div>',
  '<div class="form-group">',
    '<label for="rating">Rating:</label>',
    '<input type="text" class="form-control" id="rating">',
  '</div>',
  '<button  id= "submitted"class="btn btn-default">Submit</button>',
'</form>',
  '<body>',
'</div>',
  ].join(""),
  header: [
    '<ul class="nav nav-pills">',
  '<li role="presentation" class="disabled"><a href="http://www.imdb.com/">Link to real Imdb site</a></li>',
  '</ul>'
  ].join(""),
  footer: [
    "<h2>Footer</h2>",
    "<nav>",
    "<ul>",
    "<li>home</li>",
    "</ul>",
    "</nav>"
  ].join(""),
  editForm:[
    '<div class="edit-form display-none">',
    '<form class = "other-form" role="form">',
  '<div class="form-group">',
    '<label for="title">Movie Title:</label>',
'    <input type="text"class="form-control" value = ""  id="titles">',
  '</div>',
  '<div class="form-group">',
    '<label for="release">Release Year:</label>',
    '<input type="text" class="form-control" value = "" id="releases">',
  '</div>',
  '<div class="form-group">',
    '<label for="cover">Cover Img:</label>',
    '<input type="text" class="form-control" value = ""id="covers">',
  '</div>',
  '<div class="form-group">',
    '<label for="plot">Plot:</label>',
    '<input type="text" class="form-control" value = ""id="plotss">',
  '</div>',
  '<div class="form-group">',
    '<label for="rating">Rating:</label>',
    '<input type="text" class="form-control" value = ""id="ratings">',
  '</div>',
  '<button id = "edit" class="btn btn-default">Edit</button>',
'</form>',
  '<body>',
'</div>',
  ].join('')
};
